FROM python:3.9-slim


# install postgresql-client so we can connect to postgress db and run command
 
RUN apt-get update && \
    apt-get install -y postgresql-client-17 

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "elt_script.py"]